apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.deployment.name }}
type: Opaque
data:
  KEYCLOAK_USER: {{ .Values.secret.KEYCLOAK_USER | b64enc }}
  KEYCLOAK_PASSWORD: {{ .Values.secret.KEYCLOAK_PASSWORD | b64enc }}
  DB_ADDR: {{ .Values.secret.DB_ADDR | b64enc }}
  DB_DATABASE: {{ .Values.secret.DB_DATABASE |b64enc }}
  DB_USER: {{ .Values.secret.DB_USER |b64enc }}
  DB_SCHEMA: {{ .Values.secret.DB_SCHEMA | b64enc }}
  DB_PASSWORD: {{ .Values.secret.DB_PASSWORD | b64enc }}