apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.deployment.name }}
spec:
  ports:
  - name: {{ .Values.deployment.name }}-http
    port: 8080
    targetPort: 8080
  selector:
    app: {{ .Values.deployment.name }}
  type: {{ .Values.service.type | quote }}
