apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.pv.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.pv.path | quote }}