apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.deployment.name }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.MYSQL_ROOT_PASSWORD | b64enc }}
  MYSQL_USER: {{ .Values.secret.MYSQL_USER | b64enc }}
  MYSQL_PASSWORD: {{ .Values.secret.MYSQL_PASSWORD | b64enc }}
  MYSQL_DATABASE: {{ .Values.secret.MYSQL_DATABASE | b64enc }}

