apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.svcName }}
  labels:
    app: {{ .Values.deployment.labels }}
spec:
  selector:
    app: {{ .Values.deployment.labels }}
  type: {{ .Values.service.type | quote }}
  ports:
    - name: {{ .Values.service.svcName }}
      port: {{ .Values.service.port }}

