apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mysql-statefulset.fullname" . }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"