apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mysql-statefulset.fullname" . }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi