apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql-statefulset.fullname" . }}
  labels:
    {{- include "mysql-statefulset.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      name: mysql
  selector:
    {{- include "mysql-statefulset.selectorLabels" . | nindent 4 }}
