apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql-statefulset.fullname" . }}-headless
  labels:
    {{- include "mysql-statefulset.labels" . | nindent 4 }}
spec:
  ports:
  - name: mysql
    port: {{ .Values.service.port }}
  clusterIP: None
  selector:
    