apiVersion: v1
kind: Namespace
metadata:
  name: mysql-db
---
apiVersion: v1
kind: Secret 
metadata:
  name: mysql-secret
  namespace: mysql-db 
type: opaque
stringData:
  mysql-root: root
  mysql-user: user
  mysql-password: password

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv
  namespace:  mysql-db
  labels:
    app: mysql
    type: local
spec:
  storageClassName: microk8s-hostpath
  capacity: 
    storage: 3Gi 
  accessModes: 
    - ReadWriteOnce 
  hostPath: 
    path: "/var/data" 
---
apiVersion: v1
kind: PersistentVolumeClaim  
metadata:
  name: mysql-pvc-claim 
  namespace: mysql-db 
  labels: 
    app: mysql 
spec: 
  storageClassName: microk8s-hostpath 
  capacity: 
  accessModes: 
    - ReadWriteOnce 
  resources: 
    requests: 
      storage: 3Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: mysql-db
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql-svc"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers: 
      - name: mysql-db 
        image: mysql:5.7
        ports: 
        - name: mysql-port
          containerPort: 3306 
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
               name: mysql-secret
               key: mysql-root
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
               name: mysql-secret
               key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
               name: mysql-secret
               key: mysql-password
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc-claim
---
apiVersion: v1
kind: Service 
metadata:
  name: mysql-svc 
  namespace: mysql-db
  labels:
    app: mysql 
spec:
  ports: 
  - port: 3306 
  clusterIP: None
  selector: 
    app: mysql 

---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
  namespace: mysql-db
spec:
  containers:
  - name: mysql-container
    image: alpine
    command: ['sh','-c', "sleep 1800m"]
    imagePullPolicy: IfNotPresent
