kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv
  namespace: database
  labels:
    app: mysql
    type: local
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/data"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pv-claim
  namespace: database
  labels:
    app: mysql
spec:
  storageClassName: microk8s-hostpath
  capacity:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
