apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mysql-statefulset-v1.fullname" . }}
  labels:
    {{- include "mysql-statefulset-v1.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "mysql-statefulset-v1.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mysql-statefulset-v1.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mysql-statefulset-v1.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
      - name: {{ include "mysql-statefulset-v1.fullname" . }}
        persistentVolumeClaim:
          claimName: {{ include "mysql-statefulset-v1.fullname" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - secretRef:
              name: {{ include "mysql-statefulset.fullname" . }}
          volumeMounts:
          - name: {{ include "mysql-statefulset-v1.fullname" . }}
            mountPath: "/var/lib/mysql"
          ports:
            - name: mysql
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
