apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mysql-statefulset-v1.fullname" . }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mysql-db"