apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql-statefulset-v1.fullname" . }}
type: Opaque
data:
  MYSQL_USER: {{ .Values.mysqlUserName | b64enc }}
  MYSQL_PASSWORD: {{ .Values.mysqlPassword | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysqlRootPassword | b64enc }}
