apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql-statefulset-v1.fullname" . }}
  labels:
    {{- include "mysql-statefulset-v1.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "mysql-statefulset-v1.labels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      