apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql-statefulset-v1.fullname" . }}-headless
  labels:
    {{- include "mysql-statefulset-v1.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    name: web
  clusterIP: None
  selector:
    {{- include "mysql-statefulset-v1.labels" . | nindent 4 }}